"use strict";
let link = document.createElement("link");
link.rel="stylesheet";
link.href = "sass/task2.css";
document.head.appendChild(link);

let container = document.createElement("div");
container.setAttribute("class","container");
document.getElementsByTagName("main")[0].appendChild(container);
let row = document.createElement("div");
row.setAttribute("class","row");
container.appendChild(row);
let headings = document.createElement("div");
headings.setAttribute("class","headings");
row.appendChild(headings);
let h1 = document.createElement("h1");
let h4 = document.createElement("h4");
headings.appendChild(h4);
headings.appendChild(h1);
h4.innerText = "WHAT PEOPLE SAY";
h1.innerText = "Reviews";
let row2 = document.createElement("div");
row2.setAttribute("class","row");
row2.classList.add('psofpage');
container.appendChild(row2);
let forptext1 = document.createElement("div");
let forptext2 = document.createElement("div");
let forptext3 = document.createElement("div");
forptext1.className = "col-4";
forptext2.className = "col-4";
forptext3.className = "col-4";
row2.appendChild(forptext1);
row2.appendChild(forptext2);
row2.appendChild(forptext3);
let p1 = document.createElement("p");
let p2 = document.createElement("p");
let p3 = document.createElement("p");
forptext1.appendChild(p1);
forptext2.appendChild(p2);
forptext3.appendChild(p3);
p1.innerText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco"
p2.innerText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco"
p3.innerText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco"
let row3 = document.createElement("div");
row3.setAttribute("class","row");
row3.classList.add('imgsofpage');
container.appendChild(row3);
let forimg1 = document.createElement("div");
let forimg2 = document.createElement("div");
let forimg3 = document.createElement("div");
forimg1.className = "col-4";
forimg2.className = "col-4";
forimg3.className = "col-4";
forimg1.classList.add('contentimgsofpage');
forimg2.classList.add('contentimgsofpage');
forimg3.classList.add('contentimgsofpage');
row3.appendChild(forimg1);
row3.appendChild(forimg2);
row3.appendChild(forimg3);
let img1 = document.createElement("img");
let img2 = document.createElement("img");
let img3 = document.createElement("img");
img1.setAttribute("src","images/man1.jpg");
img2.setAttribute("src","images/man2.jpg");
img3.setAttribute("src","images/man3.jpg");
let h5first = document.createElement("h5");
let h5second = document.createElement("h5");
let h5third = document.createElement("h5");
h5first.innerText = "John Doe";
h5second.innerText = "Pete Jones";
h5third.innerText = "Mark Wilson";
forimg1.appendChild(img1);
forimg1.appendChild(h5first);
forimg2.appendChild(img2);
forimg2.appendChild(h5second);
forimg3.appendChild(img3);
forimg3.appendChild(h5third);
